{{- range $name, $settings := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-{{ $settings.data | toYaml | sha256sum | trunc 8 }}
  {{- if .Values.ns.create }}
  namespace: {{ trunc 60 (.Values.name | quote) }}
  {{- end }}
data:
{{- range $fileName, $fileContent := $settings.data }}
  {{ $fileName | quote }}:
{{ toYaml $fileContent | indent 4 }}
{{- end }}
{{- end }}
