{{- range $name, $settings := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
data:
{{- range $fileName, $fileContent := $settings.data }}
  {{ $fileName }}: |-
    {{ $fileContent }}
{{- end }}
