{{- if .Values.ns.create}}
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
  name: {{ toString (trunc 60 (.Values.name | quote)) }}
{{- end }}
