apiVersion: apps/v1
kind: {{ .Values.replicasKind }}
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.replicasKind "StatefulSet" }}
  volumeClaimTemplates:
  {{- range $volume := .Values.volumeClaimTemplates }}
  - metadata:
      name: {{ $volume.name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storageClassName: {{ $volume.storageClassName | default "standard-rwo" }}
          storage: {{ $volume.storage | default "1Gi" }}
  {{- end }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- if eq .Values.replicasKind "StatefulSet" }}
  serviceName: {{ include "app.fullname" . }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.configMaps }}
      volumes:
      {{- range $name, $settings := .Values.configMaps }}
      - name: {{ $name }}
        configMap:
          name: {{ $name }}-{{ $settings.data | toYaml | sha256sum | trunc 8 }}
      {{- end}}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end }}
          {{- if .Values.args }}
          args: {{ .Values.args }}
          {{- end }}
          {{- if or .Values.configMaps (eq .Values.replicasKind "StatefulSet") }}
          volumeMounts:

          {{- if .Values.configMaps }}
          {{- range $name, $settings := .Values.configMaps }}
          {{- range $fileName, $fileContent := $settings.data }}
          - name: {{ $name }}
            mountPath: {{ $settings.mountPath }}/{{ $fileName }}
            readOnly: true
          {{- end}}
          {{- end}}
          {{- end}}

          {{- if eq .Values.replicasKind "StatefulSet" }}
          {{- range $volume := .Values.volumeClaimTemplates }}
          - name: {{ $volume.name }}
            mountPath: {{ $volume.mountPath }}
          {{- end }}
          {{- end }}

          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- if .Values.livenessProbe }}
            {{- toYaml .Values.livenessProbe | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.defaultLivenessProbe | nindent 12 }}
            {{- end}}
          readinessProbe:
            {{- if .Values.readinessProbe }}
            {{- toYaml .Values.readinessProbe | nindent 12 }}
            {{- else }}
            {{- toYaml .Values.defaultReadinessProbe | nindent 12 }}
            {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
